name: 'rs-workspace/rust-toolchain'
description: 'GitHub actions for installing rust toolchain'
author: 'Aditya Kumar'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'arrow-down-circle'
  color: 'red'

# Define your inputs here.
inputs:
  toolchain:
    description: 'Rust Toolchain to be installed'
    default: 'stable'
  profile:
    description: 'Rust Profile to be installed'
    default: 'default'
  components:
    description: 'Rust Components to be installed'

runs:
  using: node20
  main: dist/index.js
